### ISSUE TITLE
关于论文中FLOPs的计算

### ISSUE THREAD

**Issue by icey-zhang** [Shank2358/LO-Det#3]
你好，我想问问论文中关于FLOPs的计算，为什么FLOPs2CSA = (22 + C) × WHC + 2FLOPsshuffle 为什么是22呀？这个22代表的是？

**Comment by Shank2358** [comment]
> 你好，我想问问论文中关于FLOPs的计算，为什么FLOPs2CSA = (22 + C) × WHC + 2FLOPsshuffle 为什么是22呀？这个22代表的是？

您好，感谢关注，计算过程如下，第一行是3×3的可分离卷积，第二行是1×1卷积，最后加上shuffle
![image](https://user-images.githubusercontent.com/33946139/177776756-289ba734-3501-4676-b146-623fbd8d11cb.png)
抱歉因为最近暑假，比较晚才看到这个，不好意思。如有任何问题咱们都还可以继续讨论。谢谢。

**Comment by Jcodehd** [comment]
> > 你好，我想问问论文中关于FLOPs的计算，为什么FLOPs2CSA = (22 + C) × WHC + 2FLOPsshuffle 为什么是22呀？这个22代表的是？
> 
> 您好，感谢关注，计算过程如下，第一行是3×3的可分离卷积，第二行是1×1卷积，最后加上shuffle ![image](https://user-images.githubusercontent.com/33946139/177776756-289ba734-3501-4676-b146-623fbd8d11cb.png) 抱歉因为最近暑假，比较晚才看到这个，不好意思。如有任何问题咱们都还可以继续讨论。谢谢。


您好，请问公式中小括号外面的乘2和小括号里面的+1是什么含义，据我所知DWConv的FLOPS应该是
k·k·C·Df·Df。k、C、Df分别为卷积核尺寸、输入特征图通道数和输出特征图尺寸。在论文中的一个CSP的FLOPS不应该是(3x3x(C/2)xWxH+1x1x(C/2)x(C/)2xWxH)嘛？如有不对请您指正，万分感谢。
